//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КППEntities : DbContext
    {
        private static КППEntities _context;

        public КППEntities()
            : base("name=КППEntities")
        {
        }

        public static КППEntities GetContext()
        {
            if (_context == null)
            {
                _context = new КППEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Доступ> Доступ { get; set; }
        public virtual DbSet<КПП> КПП { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Посетитель> Посетитель { get; set; }
        public virtual DbSet<Пропуск> Пропуск { get; set; }
        public virtual DbSet<Проход> Проход { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Транспорт> Транспорт { get; set; }
        public virtual DbSet<Ячейка_хранения> Ячейка_хранения { get; set; }
    }
}
