//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пропуск
    {
        public int id { get; set; }
        public Nullable<int> Код_Посетителя { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<System.DateTime> Действителен_до { get; set; }
        public Nullable<int> Код_доступа { get; set; }
    
        public virtual Доступ Доступ { get; set; }
        public virtual Посетитель Посетитель { get; set; }
    }
}
