//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проход
    {
        public int id { get; set; }
        public Nullable<int> Код_посетителя { get; set; }
        public Nullable<System.DateTime> Время_прохода { get; set; }
        public Nullable<int> Код_КПП { get; set; }
        public Nullable<bool> Вход_Выход { get; set; }
        public Nullable<bool> Транспорт { get; set; }
    
        public virtual КПП КПП { get; set; }
        public virtual Посетитель Посетитель { get; set; }
    }
}
